### PR TITLE
CONDUCT.md: update maintainers

### PR DESCRIPTION
**Pull request by scop**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [ ] Here are some details about my PR

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by enyrgy** [comment]
There's only one maintainer now? :O

**Comment by joshfriend** [comment]
nope, im here too

**Comment by scop** [comment]
Would be great if someone who knew who the maintainers actually are would push a fixed version of this PR :)

**Comment by joshfriend** [comment]
looks like `@yyuu`, `@blueyed`, and myself `@joshfriend` on this main repo. Also @obestwalter on the plugin repos, not sure why he isnt added on this one.

**Comment by scop** [comment]
Added blueyed and joshfriend using email addresses from git logs, in order they were in your message.

Would be good to apply this IMO even if it's bit-perfect, it's certainly closer to the truth than the one currently in the repo.

**Comment by obestwalter** [comment]
Hey, @yyuu added me a long time ago to the packaging maintainers. I am only sporadically using pyenv nowadays though. Still checking in **very** infrequently. So most honest thing would be to remove me from the maintainership, I guess.

**Pull request merged**
