### PR TITLE
Add CPython 3.11.8

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [ ] Here are some details about my PR

### Tests
- [ ] My PR adds the following unit tests (if any)

https://www.python.org/downloads/release/python-3118/

### CODE REVIEW

**Comment by johnklehm** [comment]
Gentlest of bumps here @native-api, hoping to land this in to address some CVEs.

**Comment by native-api** [comment]
> Gentlest of bumps here @native-api, hoping to land this in to address some CVEs.

You can bump it all the way.
As the code says, these versions are only used in MacOS if only the system-provided, unusable by Python OpenSSL is present.

**Comment by darren-recentive** [comment]
@native-api thanks for merging 🙏 , looks like CI finished, any chance we could get a release today as well?

**Comment by native-api** [comment]
> @native-api thanks for merging 🙏 , looks like CI finished, any chance we could get a release today as well?

CC @anton-petrov

**Pull request merged**
