### PR TITLE
Add CPython 3.11.0

### PR DESCRIPTION
**Pull request by noamcohen97**
CPython 3.11 was just released few minutes ago

### CODE REVIEW

**Comment by imankulov** [comment]
Hey, @noamcohen97. Thanks for adding CPython 3.11! Can we expect a release soon so we can bump the pyenv version in Homebrew?

**Comment by dorukcan** [comment]
@imankulov you can install the head version of pyenv. Using https://github.com/pyenv/pyenv-installer makes it easier then homebrew or any other package manager.

**Comment by BobDotCom** [comment]
> @imankulov you can install the head version of pyenv. Using https://github.com/pyenv/pyenv-installer makes it easier then homebrew or any other package manager.

FWIW, installing HEAD via homebrew is a simple as `brew install pyenv --head`, or if it was previously installed `brew unlink pyenv && brew install pyenv --head`.

**Comment by PastaPastaPasta** [comment]
I just tried this and got this error I am on macOS Ventura 13.0 (22A380), which may be the root of the issue? but Xcode 14.1 is not out yet, it's still in rc phase. Any thoughts?
```
Unlinking /opt/homebrew/Cellar/pyenv/2.3.5... 0 symlinks removed.
==> Cloning https://github.com/pyenv/pyenv.git
Updating /Users/pasta/Library/Caches/Homebrew/pyenv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0726e02e Add CPython 3.11.0 (#2493)
Error: Your Xcode (14.0.1) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by BobDotCom** [comment]
@PastaPastaPasta Considering Ventura was only released on monday (same day as python 3.11), it's reasonable to assume that not everything fully supports it yet. You should probably just install the rc version of Xcode, and I'm sure the stable version will release soon.

**Comment by native-api** [comment]
> I just tried this and got this error I am on macOS Ventura 13.0 (22A380), which may be the root of the issue? but Xcode 14.1 is not out yet, it's still in rc phase. Any thoughts?
> 
> ```
> Unlinking /opt/homebrew/Cellar/pyenv/2.3.5... 0 symlinks removed.
> ==> Cloning https://github.com/pyenv/pyenv.git
> Updating /Users/pasta/Library/Caches/Homebrew/pyenv--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at 0726e02e Add CPython 3.11.0 (#2493)
> Error: Your Xcode (14.0.1) is too outdated.
> Please update to Xcode 14.1 (or delete it).
> Xcode can be updated from the App Store.
> ```

That message seems to be coming from Homebrew so it's their issue. They probably don't support MacOS 13 yet.

**Comment by noamcohen97** [comment]
https://github.com/Homebrew/homebrew-core/issues/113968#issuecomment-1290752564
Seems like best solution is to install the RC

**Comment by jbrr** [comment]
@PastaPastaPasta you could download the xcode 14.1 release candidate if you don't want to wait: https://developer.apple.com/download/all/

**Pull request merged**
