### PR TITLE
Add support for Python 3.7.3

### PR DESCRIPTION
**Pull request by dannyvink**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [X] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [X] My PR addresses the following pyenv issue (if any)
N/A

### Description
- [X] Here are some details about my PR
This PR adds the build info for Python 3.7.3 which released earlier today.

### Tests
- [X] My PR adds the following unit tests (if any)
N/A

### CODE REVIEW

**Comment by chrahunt** [comment]
This is missing `copy_python_gdb`

**Comment by yyuu** [comment]
@chrahunt ugh, I should have noticed it 😞 I'll try adding it later if I can have chance....

**Comment by dannyvink** [comment]
Whoops! Sorry for leaving that out 😣

**Comment by NathanUrwin** [comment]
@yyuu Has this not been released yet?

**Comment by greysteil** [comment]
A release including this would be awesome! 🙏

**Pull request merged**
