### PR TITLE
Add PyPy v7.3.15

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description

Adds PyPy v7.3.15, released 2024-01-15.

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Blocked by full resolution of https://github.com/pypy/pypy/issues/4861

**Comment by mattip** [comment]
It seems there is some caching of the pypy source tarball downloads? The files at https://downloads.python.org/pypy/ have the new checksums. But thinking a bit more: why is pyenv downloading a source tarball? Shouldn't it prefer a precompiled binary?

**Comment by edgarrmondragon** [comment]
> It seems there is some caching of the pypy source tarball downloads? The files at https://downloads.python.org/pypy/ have the new checksums. But thinking a bit more: why is pyenv downloading a source tarball? Shouldn't it prefer a precompiled binary?

I couldn't find the rationale and I don't personally install the src tarball variants, but I found when it was first added: https://github.com/pyenv/pyenv/commit/b77ae3e0b505f2184b8f85334158c0ecb5c3e30e

**Comment by native-api** [comment]
We provide both precompiled and source versions for PyPy.

**Pull request merged**
