### PR TITLE
Anaconda 5.0.1

### PR DESCRIPTION
**Pull request by joshfriend**
I got "too many open files in system" errors trying to install on macOS, so it would be nice if someone could verify this (also linux)

### CODE REVIEW

**Comment by shoichiaizawa** [comment]
@joshfriend 

Ah, I just wanted to say that I was trying to make exactly the same commits around the same time you made these commits. I just want to tell you that while I have not tested it with the files you added, I did locally test it with the files I added by myself and they have exactly the same lines as your versions.

I only tested for **Anaconda3 5.0.1** and it was installable. I have dropped my versions, and am waiting for your versions going to the `master` branch. I sit back and wait for @yyuu or someone else review this PR 😃 

---

Apart from the files you committed, I have added **Miniconda2 4.3.30** and **Miniconda3 4.3.30**; please see my PR (pyenv/pyenv#1022) 🙏

**Comment by kjmrknsn** [comment]
+1
It would be nice if this PR could be checked and merged and Anaconda 5.0.1 could be installable via pyenv.

**Comment by joshfriend** [comment]
I got the anaconda2 installs working on macOS with 737fa7c. I still have trouble with anaconda3 "too many open files" error, but I quadruple-checked all the sha256 sums so it should at least _try_ to install. I'll continue investigating, but I just merged anyways so it doesn't hold anyone up from using the other versions/platforms.

**Comment by shoichiaizawa** [comment]
I pulled the latest `master` and try installing `anaconda3-5.0.1` and it was successful without encountering the **"too many open files in system"** error you mentioned.

It seems that there are some new executables have been added for **anaconda[23]-5.0.1** compared to the previous version:

```sh
diff <(ls ~/.pyenv/versions/anaconda3-5.0.0/bin) <(ls ~/.pyenv/versions/anaconda3-5.0.1/bin)
15a16,26
> bunzip2*
> bzcat*
> bzcmp@
> bzdiff*
> bzegrep@
> bzfgrep@
> bzgrep*
> bzip2*
> bzip2recover*
> bzless@
> bzmore*
```

I see this is why this 737fa7c workaround was needed.

I am not sure about the **"too many open files in system"** error you have encountered. I hope this is resolved sooner.

**Pull request merged**
