### PR TITLE
Travis CI: Add Xcode 12 on macOS 10.15.5

### PR DESCRIPTION
**Pull request by cclauss**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Here are some details about my PR
Add the current macOS and current Xcode to the testing.
* https://docs.travis-ci.com/user/reference/osx/#macos-version
### Tests
- [x] My PR adds the following unit tests (if any)
Travis CI

### CODE REVIEW

**Comment by anton-petrov** [comment]
I suggest to more complex changes. Upgrade from Xenial to Focal, for example. As for xcode12u, the best solution would be `xcode12` (Xcode 12.0.1).  And another important point: the more we add an environment for testing, the longer the build time will be.

**Comment by cclauss** [comment]
Travis jobs should run in parallel so the impact of adding a new env might not be a linear increase in runtime.  If turnaround time is important then perhaps we should move from Travis CI to GitHub Actions.

**Comment by cclauss** [comment]
Unfortunately, Travis CI still does not provide access to macOS Big Sur (v11)
ProductName:	Mac OS X
ProductVersion:	10.15.7

**Comment by anton-petrov** [comment]
Currently runs only 2 parallel vm's for pyenv, as know...

**Pull request merged**
