### PR TITLE
GitHub Actions: Add $PYENV_ROOT/shims to $PATH

### PR DESCRIPTION
**Pull request by cclauss**
Make sure you have checked all steps below.

```python
import os
import sys

EXPECTED_PYTHON = ${{ matrix.python-version }}
# Ensure that the actual Python is the expected Python.
assert sys.version.startswith(os.getenv("EXPECTED_PYTHON"))
```

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Here are some details about my PR
The goal of this PR was to ensure that `python` and `pip` are pointing to the pyenv installed versions.  That goal has been achieved in the current code.  Sorry for all the tweaking but the GitHub Actions code is touchy.  

### Tests
- [x] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by cclauss** [comment]
Sorry for all the tweaking but the code is very touchy.  The goal of this PR was to ensure that `python` and `pip` are pointing to the pyenv installed versions.  That goal has been achieved in the current code.

**Comment by cclauss** [comment]
Thanks to @Dinesh101041 for helping with the test that `actual Python == expected Python`.

**Comment by cclauss** [comment]
@anton-petrov Your review, please.

**Comment by anton-petrov** [comment]
Well done, @cclauss!

**Pull request merged**
