### PR TITLE
Customise `.python-version` filename for local project versions

### PR DESCRIPTION
**Pull request by nolar**
### Description

[22K+ projects](https://github.com/search?l=&q=filename%3A.python-version&type=Code) define their own `.python-version` files in their source code, version-controlled.

This file supposed to be an environment configuration, which is individual to every developer and their habits/preferences. A strict Python version to be used in a project can be opinionated. For actual code restrictions, `python_requires="==3.8.1"` of `setup.py` should be used.

This also breaks workflows when plugins like `pyenv-virtualenv` are used, with their own named versions instead of numeric Pythons. Having a fixed numeric Python version in a project assumes that all dependencies will be installed into that binary Python build instead of virtualenvs — for all projects that rely on this Python version.

With this PR, the developers will have an option to ignore the recommended Python versions in `.python-version` file of every project, and configure their own dot-file name to use by setting `PYENV_VERSION_FILENAME` on their workstations.

_The variable name looks not so good, can be discussed._

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

- [ ] Here are some details about my PR

### Tests
- [x] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by clbarnes** [comment]
My (admittedly somewhat unfeeling) personal opinion:

22,000 projects are wrong, and when they figure that out because their development environments start showing problems, they'll delete the file, stick it in the gitignore, and everyone will be better off for it with next to no effort on their part. I suspect that you'd find thousands of projects with vim swap files and git merge temporary files committed too, but it's not up to the vim and git developers to overcomplicate their product because people aren't using the *simple* version of it correctly.

**Comment by nolar** [comment]
@clbarnes Do they also put local paths like `/Users/nolar/src/…` into git-committed `.env`?

Precise patch-versions of Python are too specific to a local environment and a configuration of a workstation: some versions can be installed, some are not. Do I really need _all_ Python versions if I have many repos locally, or `3.8.1` is enough for all `>=3.8,<3.9` projects?

Specific binary builds like `3.8.1` as de-facto virtualenvs are problematic too, as long as they will be shared by 2+ projects that decided to pin that exact version for no reason. Can you find an ironic equivalent of such a dependency mess created by `.env` files without any way to opt out of this madness?

**Comment by clbarnes** [comment]
I completely agree with all of your points about why projects shouldn't commit `.python-version` to source control. IMO, the solution is to not do that, and for developers who understand what the file is for to raise PRs with well-reasoned and objectively correct descriptions.

**Comment by native-api** [comment]
> You already can opt out by setting the `PYENV_VERSION` envvar which overrides any version derived from CWD.

If you wish a more permanent approach of being a rebel and using the codebase contrary to its maintainer's wishes (while still using the same version control) -- you go the route of https://softwareengineering.stackexchange.com/questions/214614/how-to-maintain-a-forked-git-repo-with-feature-branches-that-upstream-wont-pull like with any other changes that upstream won't accept.

**Comment by native-api** [comment]
Ther's yet another downside to an envvar. It will affect _all_ projects, not just the one that you have a problem with.

**Comment by native-api** [comment]
Closing since you can already do what you want -- and with an envvar, too.

If you want to automatically set it whenever you're in the specific subtree, you can use https://github.com/cxreg/smartcd for that.

**Pull request closed without merging**
