### PR TITLE
supporting pip install pyenv

### PR DESCRIPTION
**Pull request by kirankotari**
#272 Change in pyenv structure to support pypi

command `pip install pyenv --target $HOME/.pyenv`
How to get updates: add the installed path to eash_install.pth file to recognise pyenv by pip

### CODE REVIEW

**Comment by kirankotari** [comment]
@yyuu update the paths in test files. 

Expected in following location: **pyenv.bats**

```bats
@test "default PYENV_ROOT" {
  PYENV_ROOT="" HOME=/home/mislav run pyenv root
  assert_success
  assert_output "/home/mislav/.pyenv"
}
```

**Comment by joshfriend** [comment]
why was it necessary to relocate **nearly 600** files?

**Comment by yyuu** [comment]
We have once tried to support PyPI as https://github.com/pyenv/pyenv-installer/pull/16 (thanks to @obestwalter ). However, we ended up to abandon the approach since it just added extra complexity and dependencies more than benefit. I don't mean supporting PyPI is worthless, but I would never prefer this to be merged into the pyenv's main repo.

**Comment by kirankotari** [comment]
I too agree of not getting merged and changing nearly 600 files is not good. The new structure is like python package which is recognised by pypi and pip install. 

when I am porting pyenv for windows, I have successfully able to do `pip install pyenv-win` thought the similar approach might help pyenv.

**Comment by kirankotari** [comment]
Checking for alternative solutions without changing the structure.

**Pull request closed without merging**
