### PR TITLE
use -I with ensurepip

### PR DESCRIPTION
**Pull request by xaocon**
Helps to workaround #2417

The `-s` flag assures that nothing can be installed to user site-package but doesn't seem to keep `ensurepip` from looking there for pip. If pip is installed in the user site-package directory pip isn't installed for the newly built python. `-I` leaves user site-package out entirely during the pip installation.

### CODE REVIEW

**Comment by xaocon** [comment]
May also fix https://github.com/asdf-community/asdf-python/issues/148 and https://github.com/asdf-community/asdf-python/issues/127.

**Comment by native-api** [comment]
While this will install Pip in the https://github.com/pyenv/pyenv/issues/2417 case -- it won't be actually used, will it?
The Pip installation in user site-packages will prevail.

That's not a bad thing though -- if it works correctly.

Will this trigger distro-specific customizations of the system Pip for Pyenv-installed Pythons?

**Comment by xaocon** [comment]
Yes, by default the user site packages are still going to be first in `sys.path`. Users could use the same workaround or others to make sure to use the version of pip installed by `python-build` if they care too. The main problems I wanted to solve was providing some additional consistency to the builds and assuring pip shims work correctly. This problem breaks the pip shims for both pyenv and asdf-python which has to be a relatively large population of python users. Even if having a version of pip installed in local won't be that common this affects a lot of people.

I'm not sure I understand the last question, could you point me at an example?

The change does cause `make test-build && make test` to pass on my system now.

**Comment by native-api** [comment]
> I'm not sure I understand the last question, could you point me at an example?

Distros patch the system-provided Pip to better suit the distro's ecosystem.
E.g. for https://packages.ubuntu.com/jammy/python3-pip, the patches they apply can be found in http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_22.0.2+dfsg-1ubuntu0.3.debian.tar.xz , `patches` directory.

I was wondering: if one
* installs an upgrade for the system's Pip with `pip3 install -U pip` (which goes into `~/.local/lib/pythonX.Y/site-packages`)
* switches to a Pyenv-provided version with the same `X.Y`
* uses Pip from it
* => will the distro patches have an effect?

---

Anyway, I've just checked that no, they don't.
By checking in Ubuntu Jammy:

```python
>>> import pip._vendor.certifi
>>> pip._vendor.certifi.core.where()
```

With distro patches, it should print `'/etc/ssl/certs/ca-certificates.crt'`.
But it prints the unpatched value, `'<home dir>/.local/lib/python<X.Y>/site-packages/pip/_vendor/certifi/cacert.pem'`.

---

So, we're clear to go.

**Pull request merged**
