### PR TITLE
Use associative arrays for performance on bash >= 4

### PR DESCRIPTION
**Pull request by scop**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - N/A

### Description
- [x] Here are some details about my PR

This makes use of bash associative arrays for speedups, see individual commit messages for details. These are quite noticeable at shell startup.

Will submit the same PR's to rbenv.

~Note: associative arrays are available starting from bash 4.0. I didn't find a reference which bash versions should pyenv work with, but bash 4.0 is already pretty old. If that's a no go, the implementation could be reworked so that it defines different function implementations for different bash versions.~ Reworked.

### Tests
- [x] My PR adds the following unit tests (if any)

N/A

### CODE REVIEW

**Comment by yyuu** [comment]
As far as I know, macOS is still shipping its BSD-based system along with bash 3.x even in 2021 (I'd speculate it is because of license concern, but, I'm not confident). Dependency to bash 4+ features might not be a very good idea until this situation to be changed 🤔 

```
% sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114
% /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by scop** [comment]
I don't think that will ever change, and it would be a shame to keep the rest of the world stuck in the past just because of that. On the other hand, newer bash versions are available for macOS, they're just not there by default.

**Comment by scop** [comment]
Oh, but then again, I didn't even remember that I already _did_ rework this so that it still works with bash < 4 as well, check out the patch contents.

**Comment by anton-petrov** [comment]
Since in macOS 10.15 Catalina the default shell is zsh, the situation is changing to the good. But we can't just lose compatibility with other systems that still use bash 3. So, can we drop bash 3 support? In any way, this is an important case to be discussed. Maybe we need compatibility layer, or something similar. For example, in [pyenv-init ](https://github.com/pyenv/pyenv/blob/master/libexec/pyenv-init) do some checks for the shell version.

**Pull request merged**
