### PR TITLE
Split startup logic into PATH and everything else

### PR DESCRIPTION
**Pull request by native-api**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/1649

### Description
- [x] Here are some details about my PR

* Implements https://github.com/pyenv/pyenv/issues/1649#issuecomment-694388530 .
* Adds a warning on shell startup if ~./profile` entry is not present -- to facilitate migration
* (unrelated) fixes expanding `PATH` in one of test descriptions

### Tests
- [x] My PR adds the following unit tests (if any)

* Test for the added warning

### CODE REVIEW

**Comment by anton-petrov** [comment]
@native-api , to reflect the changings which brings this PR, still need to synchronize that with [pyenv-installer](https://github.com/pyenv/pyenv-installer) before merging to master. Will you do a PR to pyenv-installer?

**Comment by luzfcb** [comment]
Since it is this pull request that changes the behavior of pyenv that has existed for years, it would make sense to explain here (even if again) why this change was necessary?

Actually, I ignore the existence of .profile and .bash_profile, and everything works fine for years (before this change) in .bashrc via pyenv installed by my walkthrough https://gist.github.com/luzfcb/1a7f64adf5d12c2d357d0b4319fe9dcd .

It would probably be good to inform the community of best practices and why to run
the new `eval "$ (pyenv init --path)"` on .bashrc/.zprofile can be a bad idea.

Are all README instructions up to date?

**Comment by luzfcb** [comment]
This pull-request and some related changes in other pull-requests change anything in the plugin load logic?
I use pyenv-virtualenvwrapper and it works very well, but its code has not been touched by anyone for 4 years.

https://github.com/pyenv/pyenv-virtualenvwrapper

**Comment by native-api** [comment]
>  why this change was necessary?

> [x] My PR addresses the following pyenv issue (if any)
> 
>     * Closes #1649

> Are all README instructions up to date?

No. https://github.com/pyenv/pyenv/pull/1920 fixes that.

> This pull-request and some related changes in other pull-requests change anything in the plugin load logic?

Not to my knowledge.

However, the plugins that add their entries to `PATH` also suffer from a problem the same as #1649 and will need their startup logic split if that's to be fixed.

**Pull request merged**
