### PR TITLE
GitHub actions tests

### PR DESCRIPTION
**Pull request by native-api**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Here are some details about my PR

* Add running `make test` in Github Actions now that Travis check no longer runs; fix failures.
* Add diagnostic output to test libraries hat makes it possible to diagnose errors.

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by joshfriend** [comment]
Any reason you kept the Travis CI config around still?

**Comment by native-api** [comment]
@joshfriend I don't know why it was disabled -- that certainly wasn't me. So until that is clarified, I didn't think it was a good idea to touch it.

**Comment by joshfriend** [comment]
I didn't disable it, but it's probably for the best given the Travis CI security incident, although I don't know how to revoke the github API key or whatever travis is using to create releasees for tags

**Comment by native-api** [comment]
> given the Travis CI security incident
I read their bulletin. According to it, it only exposed secret variables to external PR builds (PR builds where the PR branch is from a fork) -- so they could leak if a PR had malicious code.
There have been no PRs with any suspect of malicious code in that timeframe here, and the secret value is included in such a way that it's hard to access from build logic (need to parse Travis' autogenerated script to my best knowledge, so code doing smth like that would be quite obvious).
> I don't know how to revoke the github API key or whatever travis is using to create releasees for tags
I don't see any kind of access keys in this repo's settings. Personal tokens can be used for releases. Since @anton-petrov is doing the releases, I guess it's his personal token encrypted in `.travis,yml`.

**Comment by native-api** [comment]
> Since @anton-petrov is doing the releases, I guess it's his personal token encrypted in .travis.yml.

Checking Git Blame, @yyuu added the encrypted value. So it must be his.

As mentioned earlier, I believe it's highly unlikely that it has leaked -- yet he can revoke that token nevertheless just for the peace of mind.

**Comment by yyuu** [comment]
Hmm, I couldn't figure out how to revoke my Travis token 🤔  Maybe uninstall & re-install the GitHub App for Travis works...? Maybe it's a better idea to consider migrating to GitHub Actions completely... 🙊

**Pull request merged**
