### PR TITLE
Fix OpenSSL 3.3.2 download URLs

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description

See https://github.com/pyenv/pyenv/pull/3050#issuecomment-2342491510.

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by native-api** [comment]
Fixed in https://github.com/pyenv/pyenv/pull/3060

**Comment by native-api** [comment]
Oh. Noticed I've used a wrong version for 3.12+

**Comment by jschwager** [comment]
@edgarrmondragon Just curious as to what your release schedule looks like for pyenv? Anyone in my org who has installed the latest release before the recent commits to resolve the OpenSSL errors is still obviously receiving errors during the Python build process for impacted versions.

**Comment by edgarrmondragon** [comment]
@jschwager I don't really manage releases here and I'm just a regular contributor 😄, but see https://github.com/orgs/pyenv/discussions/2940.

**Comment by jschwager** [comment]
@edgarrmondragon My apologies! For some reason I thought pyenv was your project.

**Comment by native-api** [comment]
@jschwager Made https://github.com/pyenv/pyenv/releases/tag/v2.4.13
But your problem must be something else because these URLs are only used in MacOS without Homebrew.

**Pull request merged**
