### PR TITLE
Added Miniforge 3

### PR DESCRIPTION
**Pull request by anton-petrov**
Added latest Miniforge3-4.9.2-5 support for all platforms, including arm64 in macOS for Apple M1, macOS x86_64, Linux x86_64, Linux ppc64le (POWER8/9).

Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [ ] Here are some details about my PR

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by gokhan275** [comment]
Leave

**Comment by baubaid** [comment]
Looking to get miniforge using pyenv. Is this working at the moment? Should I be seeing it listed when I do `pyenv install --list`?

**Comment by anton-petrov** [comment]
Yes, of course.
```
❯ pyenv install --list | grep miniforge
  miniforge3-4.9.2
```

**Comment by baubaid** [comment]
@anton-petrov Odd; I do not see it. `pyenv install --list | grep miniforge` doesn't output anything. I'm running pyenv 1.2.22 by the way.

Maybe it will be available in the next release? I just noticed that 1.2.22 came out roughly at the same time as this PR.

**Comment by anton-petrov** [comment]
Hi, @baubaid. It depends on how exactly you install _pyenv_. If you installed _pyenv_ using **git** or **pyenv-installer,** you can execute these command: `cd ~/.pyenv && git pull` to have the latest version. Or, wait for the next release...

P.S.: In any case, you can go to the directory where _pyenv_ was installed and execute the command `git pull` to update.

**Comment by baubaid** [comment]
Thank you, @anton-petrov ! I actually installed it via Homebrew, so I think I'll just wait for the next release for the time-being.

**Pull request merged**
