### PR TITLE
Add Python 3.8.0 (stable release)

### PR DESCRIPTION
**Pull request by AnonGuy**
Adds the Python 3.8.0 stable release to `python-build`.

### CODE REVIEW

**Comment by patrick91** [comment]
@AnonGuy maybe you should also update this line: https://github.com/pyenv/pyenv/blob/master/.travis.yml#L29

**Comment by AnonGuy** [comment]
@patrick91 Thanks for the heads up!

**Comment by jonadaly** [comment]
@AnonGuy I think you've added the release note to the wrong section (1.2.13 has already been released)

**Comment by joshfriend** [comment]
Thanks @AnonGuy ❤️

**Comment by chetankapoor** [comment]
I tried to install Python on Ubuntu but it failed
`root@dd07112a861c:~/.pyenv# bin/pyenv install 3.8.0
Downloading Python-3.8.0.tgz...
-> https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
error: failed to download Python-3.8.0.tar.gz

BUILD FAILED (Ubuntu 18.04 using python-build 1.2.14)
`

**Comment by joshfriend** [comment]
@chetankapoor please open a new issue and follow the issue template if you are having issues with this, currently you have provided no useful information for debugging your problem.

https://github.com/pyenv/pyenv/wiki/Common-build-problems

**Comment by vegarsti** [comment]
How can I get this from homebrew? It says I have the latest version

**Comment by hugovk** [comment]
Homebrew are in the process of adding Python 3.8.0, please see https://github.com/Homebrew/homebrew-core/pull/45337.

**Comment by vegarsti** [comment]
Awesome, thanks @hugovk

**Comment by patrick91** [comment]
Not sure that PR involves pyenv though, I think it only relates to brew's python version. @joshfriend what's the process of updating pyenv on brew?

**Comment by vegarsti** [comment]
@patrick91 Issue [here](https://github.com/Homebrew/homebrew-core/pull/45365), it seems!

**Pull request merged**
