### PR TITLE
Add CPython 3.10.8

### PR DESCRIPTION
**Pull request by MuXodious**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [ ] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Released on 11/10/2022
- [x] https://www.python.org/downloads/release/python-3108/

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by tobixx** [comment]
Hi, may I ask if there is a reason why not also 3.9.15, 3.8.15, 3.7.15 was added ?

**Comment by MuXodious** [comment]
> Hi, may I ask if there is a reason why not also 3.9.15, 3.8.15, 3.7.15 was added ?

Nope, there are no spesific reasons not to add any of those versions. I personally needed 3.10.8 and then created this commit. You can add them yourself by following [CONTRIBUTING.md](https://github.com/pyenv/pyenv/blob/master/CONTRIBUTING.md). I can try adding them myself too, if nobody else does, once I have spare time. ✌️

**Comment by adamchainz** [comment]
I've opened #2482 to add the three missed releases.

**Comment by NEXT-JP** [comment]
Seems like the comment from @tobixx underscores a question I've always had; Why hasn't the process of adding new releases of python versions and creating a new PyEnv release been automated. It always seems to take a few weeks for the latest Python version to be available in the latest PyEnv release.

**Pull request merged**
