### PR TITLE
CPython 3.9.10 and 3.10.2

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by native-api** [comment]
See https://github.com/pyenv/pyenv/pull/2218 on comments about 3.10.2

**Comment by nedbat** [comment]
I'm sorry, I don't know how to decide if we can upgrade the dependencies.

**Comment by native-api** [comment]
You can test if all the tests pass with OpenSSL 3, for both versions (they should).
About Readline, I'm pretty sure we can upgrade it (it's only used in MacOS without Homebrew anyway).

**Comment by fredrikaverpil** [comment]
Ping @tiran - sorry for bringing you into this conversation seemingly randomly 😅 would you say it's wise for pyenv to provide CPython 3.10.2 compiled against openssl 3?

**Comment by native-api** [comment]
We'd like to do the same for 3.9.10+ since [they backported OpenSSL 3 support there, too](https://bugs.python.org/issue38820).

**Comment by tiran** [comment]
Python's OpenSSL 3.0 is preliminary and experimental. I recommend against using Python with OpenSSL 3.0 in production environments. There are known performance regressions and problems. Also OpenSSL 3.0 is new and a lot of code has changed.

**Comment by native-api** [comment]
@tiran Thanks, that's a very valuable info!
Is there any kind of milestone in plans so that we know when to switch?

**Comment by tiran** [comment]
No ETA yet. Somebody needs to put in the work and review CPython's use of OpenSSL APIs. See also https://mail.python.org/archives/list/python-dev@python.org/thread/ATO4DM6QYZGLSGGDZ3TRN5X3QDD5OHOE/

**Comment by fredrikaverpil** [comment]
@tiran thank you for both this input and your invaluable contributions to python. 🙏

**Comment by SnoopJeDi** [comment]
Does `pyenv` have a policy about which versions of these dependencies should be included in a build recipe? I wondered about this when I put #2218 together, but erred on the side of keeping what was used for `3.10.1`. This would be a helpful thing to document in a `CONTRIBUTING.md` file.

**Comment by fredrikaverpil** [comment]
@SnoopJeDi I agree with you. +1 on having some sort of guidance here and I am not aware of one. Ping @anton-petrov ☝️

**Comment by anton-petrov** [comment]
@fredrikaverpil We don't have any policy about the versions of third party libraries that are used for building CPython yet...
But, as I see, there are problems with opensl at the moment, suggest compiling with OpenSSL 1.1.1, not a version 3.
@SnoopJeDi 
> This would be a helpful thing to document in a CONTRIBUTING.md file.
That's a good idea! We need to do that in the near future.

**Comment by anton-petrov** [comment]
@tiran 
> Python's OpenSSL 3.0 is preliminary and experimental. I recommend against using Python with OpenSSL 3.0 in production environments. There are known performance regressions and problems. Also OpenSSL 3.0 is new and a lot of code has changed.

Thanks for this important information!

**Pull request merged**
