### PR TITLE
Adding micropython 1.20

### PR DESCRIPTION
**Pull request by frozenwizard**
Make sure you have checked all steps below.

### Prerequisite
* [ ] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [x] Here are some details about my PR
Adds micropython 1.20 support
### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by frozenwizard** [comment]
So new to this repo. The builds failed due to a missing dependency  axtls. Is that an issue with my change or unrelated?

**Comment by native-api** [comment]
If there are flavor-specific prerequisites, you should be installing them for the specific flavors as part of CI -- i.e. in the corresponding jobs of `.github/workflows/modified_scripts_build.yml`.

**Comment by native-api** [comment]
Btw I don't see `axtls` as a dependency at https://docs.micropython.org/en/latest/develop/gettingstarted.html#required-dependencies

**Comment by frozenwizard** [comment]
Ok. I'll take a look over the weekend.

**Comment by frozenwizard** [comment]
Yea so it looks like axtls and has been replaced with mbedtls.

**Comment by native-api** [comment]
Looks like there's a problem with the release: tt tries to build a dependency that's no longer being included.

**Pull request closed without merging**
