### PR TITLE
Add PyPy 7.2.0

### PR DESCRIPTION
**Pull request by wizpig64**
https://pypy.readthedocs.io/en/latest/release-v7.2.0.html

Marked as draft until squeaky/portable-pypy updates their builds: https://github.com/squeaky-pl/portable-pypy/issues/94

### CODE REVIEW

**Comment by joshfriend** [comment]
Fantastic, thank you 😄

**Comment by fschulze** [comment]
They are available now

**Comment by squeaky-pl** [comment]
You will need to change urls to github since I abandoned Atlassian Bitbucket.

**Comment by wizpig64** [comment]
Updated to squeaky's new urls and hashes.

Thanks all!

**Pull request merged**
