### PR TITLE
Add release process checklist to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by amureki**
### Description

While checking if there is a new release containing Python 3.11, I stumbled upon discussion in #2474.
I decided to contribute to the docs here with a summary checklist of things to be done for a new release.
I am also happy to help with the new releases, if this is suitable.
The process is quite similar to what [we are doing in model-bakery](https://github.com/model-bakers/model_bakery/releases/), but we also have a GitHub action hooked to every new git tag that drafts a release in PyPI (which in your case is not needed).

Best,
Rust

### CODE REVIEW

**Review by native-api — COMMENTED** [review]
Do you think this belongs in CONTRIBUTING.md? This is not for contributors but rather for maintainers.

We would benefit from a Github action that would create a formula bump PR in Homebrew. Rbenv has one. But I don't know if we would have access to the PR branch if a mechanical bump doesn't work and needs adjustment (this happened before).

**Comment by amureki** [comment]
> Do you think this belongs in CONTRIBUTING.md? This is not for contributors but rather for maintainers.
> 
> We would benefit from a Github action that would create a formula bump PR in Homebrew. Rbenv has one. But I don't know if we would have access to the PR branch if a mechanical bump doesn't work and needs adjustment (this happened before).

Releasing is also a way of contributing, but I agree, we could separate this to a different page. Feel free to add comments on naming and wording there!

~~~

Regarding the automated release - https://github.com/rbenv/rbenv/blob/master/.github/workflows/release.yml does seem rather simple, but seems to need a token. [Action docs](https://github.com/mislav/bump-homebrew-formula-action).
I am not sure I am fully following you.
The way I see the process:
 - a maintainer creates a PR with the new version (or directly pushes it to main branch)
 - then they draft a new release via GitHub interface with the new tag
 - New tag on GitHub triggers "bump-homebrew-formula-action" to run
 - Profit?

But I am not yet familiar with homebrew processes, happy to get more input.

**Review by native-api — APPROVED** [review]

**Comment by native-api** [comment]
Okay, now about the releasing.

I can assign you permissions sufficient to create releases.

However, you must know that the upcoming release is supposed to be a special one.

For the first time, we're going to use donated money to fund development. Namely, I'm going to take some funds for implementing https://github.com/pyenv/pyenv/pull/2487 which was the most requested feature. Yuu may also take something for his past contributions as the project's founder and by far the largest contributor. (We've discussed this in the team chat some time ago.)

So in the release notes, we need to specifically and prominently inform readers of this, thank all our past sponsors for making this -- and specifically the feature -- possible, and add a section at the bottom listing them. In the following releases, we're going to list sponsors since the last release.

This is crucial because this is long overdue: we've set up sponsorship near the end of the last year IIRC and have yet to acknowledge them!

From what I can see, donors can be seen in the Github Sponsors dashboard, even without any special permissions. Some donate directly to our Open Source Collective, they can also be seen there without any special rights.

**Comment by amureki** [comment]
@native-api fantastic idea to mention beloved sponsors! And you guys definitely deserve this funding.
I drafted some notes for the upcoming release, please, share your thoughts if you'd see it differently, or correct me if I missed something or someone:

--- 

```
## Thanks to Sponsors

This release was possible thanks to our community and specifically to:

* @samuelcolvin
* @deronnax
* @subecho
* @getsentry
* @thijsmie
* @jgigliotti
* @9bow
* @gabrielmbmb
* @xoflare
* [38elements](https://opencollective.com/38elements)
* [Pedro R.](https://opencollective.com/pedro-r)

If your company wants to support the development or to give some love to pyenv, you can join our supporters by:

* https://github.com/sponsors/pyenv
* https://opencollective.com/pyenv


## What's Changed
* ...

```

**Comment by native-api** [comment]
Okay, here're my thoughts:

> ## What's Changed
> * ...
The sponsors section should definitely be at the bottom since it's an addendum, the main topic is the release. Placing it above would give it undue weight and IMO would look like we're trying to such up to the backers.

> * samuelcolvin
> * deronnax
> * subecho
For the same reason, it should be short and to the point -- which means writing them out in one line.

I'd also choose a more formal style. We're a high-profile project, IMO it'd be better to project an image of a mature, reliable organization that their money would be safe with and put to appropriate use (which we are and do, but still it'd be better to show that as well) -- by giving appropriate credit where it's due yet keeping our dignity.

I'd write smth like this:

> Sponsors
> ======
> 
> For the first time, we've used your donated money to fund the project's development. In particular, to implement the most requested feature, [Auto-resolve prefixes to the latest version](https://github.com/pyenv/pyenv/pull/2487).
> 
> As such, we're finally giving the long-overdue credit to our generous sponsors! Thank you, guys, for making this possible!
> 
> &lt;list the sponsors&gt;

**Comment by amureki** [comment]
Perfect. But we would mention all the backers I mentioned, right? I hope I did not forget anyone...

```
## What's Changed

* ...

## Sponsors

For the first time, we've used your donated money to fund the project's development. In particular, to implement the most requested feature, [Auto-resolve prefixes to the latest version](https://github.com/pyenv/pyenv/pull/2487).

As such, we're finally giving the long-overdue credit to our generous sponsors! Thank you, guys, for making this possible!

@samuelcolvin, @deronnax, @subecho, @getsentry, @thijsmie, @jgigliotti, @9bow, @gabrielmbmb, @xoflare, [38elements](https://opencollective.com/38elements), [Pedro R.](https://opencollective.com/pedro-r)
```

I am also happy if you would want to draft this release. 
In the end I think we came up with a good announcement, and in the same time I was not involved in any development here, but rather had an intention to push this to the finish line.
Also, if you'd need my further input, I am available 👍

**Comment by native-api** [comment]
> I hope I did not forget anyone...

Need to mention "past sponsors" from https://github.com/sponsors/pyenv, too. "Current" must be "last donation was no longer than X ago" (looks like no longer than a month or has an ongoing subscription). But since we've never ever did that yet...

**Comment by amureki** [comment]
@native-api updated my previous message to include 7 past sponsors, good point. 👍 

And thank you for the invitation. I am ready to draft a new GitHub release according to our freshly documented process.
Then I could dig into brew releases and prepare a PR into https://github.com/Homebrew/homebrew-core/commits/master/Formula/pyenv.rb

**Comment by native-api** [comment]
I almost forgot. Under https://github.com/pyenv/pyenv/pull/2487 's entry in the release notes, we should mention the caveats outlined in the PR's description.

**Comment by amureki** [comment]
> I almost forgot. Under #2487 's entry in the release notes, we should mention the caveats outlined in the PR's description.

Added!

**Comment by amureki** [comment]
@native-api so I will proceed with the GitHub release. Also, in case something will go wrong, release descriptions are editable.

**Comment by amureki** [comment]
Release is in place:
https://github.com/pyenv/pyenv/releases/tag/v2.3.6

I also created a PR in homebrew:
https://github.com/Homebrew/homebrew-core/pull/114597

**Pull request merged**
