### PR TITLE
Updated README with correct path for zsh

### PR DESCRIPTION
**Pull request by vmesel**

### CODE REVIEW

**Comment by blueyed** [comment]
That really depends, and makes it slower in general.

**Comment by tukushan** [comment]
Installing into `~/.zshenv` didn't work for me but `~/.zshrc` did.

**Comment by blueyed** [comment]
@tukushan 
Have you logged out and in again?

**Comment by andrebautista** [comment]
Can confirm this change is necessary. It seems as though the .zshenv paths are being added after usr/bin and usr/local/bin. When I move them to the .zshrc file the pyenv paths are added before and the correct python version is used.

**Comment by anton-petrov** [comment]
Already corrected.

**Pull request closed without merging**
