### PR TITLE
allow tcl-tk as argument or try with homebrew by default

### PR DESCRIPTION
**Pull request by grahamannett**
Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/1125
For anyone trying to use tcltk from homebrew before (or if you had tcltk installed from homebrew tkinter would fail I believe)
 #1125 
### Description
- [x] Here are some details about my PR

I previously added the regex match for this, but having to pass the config opts everytime while other packages use homebrew by default made this seem worthwhile.  If there is anything that would make this more streamlined, or a better place to put it in python-build then let me know.  

This should hopefully allow more people to use pyenv and things like matplotlib or whatever that may previously had issues.

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by grahamannett** [comment]
can this get looked at @yyuu or someone else?  itd be helpful for installing 3.8.0 and those of use who use install pyenv --HEAD from brew

**Comment by grahamannett** [comment]
Can this be merged so users of asdf can use python-build and not run into problems?

**Comment by grahamannett** [comment]
@joshfriend or @yyuu any interest in merging this?

**Comment by joshfriend** [comment]
can you fix the tests?

**Comment by grahamannett** [comment]
@joshfriend im not sure i understand travis-ci enough to know why it is failing.  locally my tests run exactly the same.  maybe ill try again and see if i can add a test for the gui portion as it seems plausible and im worried i will create issues for linux users

**Pull request closed without merging**
