### PR TITLE
describe how to use versions alongside system

### PR DESCRIPTION
**Pull request by niccokunzmann**
### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - Closes https://github.com/pyenv/pyenv/issues/XXXX

### Description

The order of the versions for `pyenv global` have a meaning.  #2406 shows this.
This documents what to do to keep the system default python
version as the version to be used for all commands for the major version but at the same time expose the other installed Python versions with their major and minor versions to PATH.
I.e. python3 -> system
python3.10 -> system
python3.9 -> pyenv
python3.8 -> pyenv
...

To use with tox.

I realize that this is something to be discussed in the forum. If that needs to happen first, please close the issue.
Although, this would have saved my some minutes of searching and trying out.

### Tests

none, documentation

### CODE REVIEW

**Review by native-api — COMMENTED** [review]
Please report the problem that this is supposed to solve, preferrably as an issue with the necessary diagnostic info.

Pip3 segfaults usually have nothing to do with version order so the proposed change seems irrelevant so far.

**Comment by niccokunzmann** [comment]
@native-api, I described more clearly what this documentation solves for me. Also, I opened the issue #2406 which this does not solve.

**Review by native-api — CHANGES_REQUESTED** [review]
In the case you've reported, `pip3` corresponds to 3.6.15 -- because all Python 3 installations provide the `pip3` executable and 3.6.15 is the first in the list.

Indeed, if you wish `pip3` to correspond to the system version, you need to specify `system` before other py3 installations -- but that won't fix the segmentation fault with 3.6.15's Pip.

---

So the proposed text is incorrect as written -- it's not a requirement write `system` first as it says.

---

It will however be okay if it's rewritten to instead explain this peculiarity with `pip3`. (That is, if multiple selected installations provide an executable, the first one in the list that does wins.)

**Comment by niccokunzmann** [comment]
That sounds like a good proposal to me. I will change it when I find the time.

**Comment by native-api** [comment]
It's probably also better to place it into https://github.com/pyenv/pyenv#understanding-python-version-selection because this mechanic is not specific to `pyenv global`.

**Pull request closed without merging**
