### PR TITLE
Add PyPy 3.7-7.3.2 (source distribution)

### PR DESCRIPTION
**Pull request by brechtm**
Not tested!

### CODE REVIEW

**Review by native-api — APPROVED** [review]
Tested the PR in Bionic AMD64. All correct.

**Comment by pythoninthegrass** [comment]
Any movement on this? Seeing `pypy3.6-7.3.1` as the most current pypy option under pyenv 1.2.21 ¯\_(ツ)_/¯

**Comment by Czaki** [comment]
When it will be merged?

**Comment by fievelk** [comment]
This would be really helpful!

**Review by yyuu — APPROVED** [review]

**Pull request merged**
