### PR TITLE
GitHub Action to build Python versions on Ubuntu

### PR DESCRIPTION
**Pull request by cclauss**
GitHub Action to install the following Python versions on Ubuntu 20.04 Focal Fosa.
`python-version: [2.7.18, 3.5.10, 3.6.13, 3.7.10, 3.8.8, 3.9.2]`

Output: https://github.com/cclauss/pyenv/actions

https://www.python.org/downloads and https://devguide.python.org/devcycle/#end-of-life-branches

Make sure you have checked all steps below.

### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [ ] My PR addresses the following pyenv issue (if any)
  - https://github.com/pyenv/pyenv/issues/XXXX

### Description
- [ ] Here are some details about my PR

### Tests
- [ ] My PR adds the following unit tests (if any)

### CODE REVIEW

**Comment by cclauss** [comment]
@anton-petrov This PR does what I hoped that it would do.

**Comment by cclauss** [comment]
So...  It installs the requested version of CPython but does not set `python` to point to it.

**Comment by anton-petrov** [comment]
> So... It installs the requested version of CPython but does not set `python` to point to it.
@cclauss 
Do you think this PR is ready for review/merge, or work still in progress?

**Comment by cclauss** [comment]
It is ready to merge.  Thanks.

**Pull request merged**
