### PR TITLE
Add ability to easily skip all use of Homebrew

### PR DESCRIPTION
**Pull request by samdoran**
### Prerequisite
* [x] Please consider implementing the feature as a hook script or plugin as a first step.
  * pyenv has some powerful support for plugins and hook scripts. Please refer to [Authoring plugins](https://github.com/pyenv/pyenv/wiki/Authoring-plugins) for details and try to implement it as a plugin if possible.
* [x] Please consider contributing the patch upstream to [rbenv](https://github.com/rbenv/rbenv), since we have borrowed most of the code from that project.
  * We occasionally import the changes from rbenv. In general, you can expect changes made in rbenv will be imported to pyenv too, eventually.
  * Generally speaking, we prefer not to make changes in the core in order to keep compatibility with rbenv.
* [x] My PR addresses the following pyenv issue (if any)
  - None

### Description

This has been discussed and turned down before ( #1686, #1715) and the [suggestion](https://github.com/pyenv/pyenv/issues/1715#issuecomment-929531904) was to make `brew` a noop. That's what I do but it would be nice if there was a simpler way for `pyenv` to handle this. Having to make `brew` a noop, then fix it for normal use is not hard but it gets tiresome (I compile Python a lot 🤓).

I came up with a solution using an environment variable `PYENV_DISABLE_HOMEBREW`. I wanted to open a PR and discuss adding this to `pyenv`.

If it's something that would be considered, I'd be happy to work on documentation and tests.

### Tests
- [ ] None yet

### CODE REVIEW

**Comment by samdoran** [comment]
cc @sivel

**Comment by native-api** [comment]
Where are you going to take deps from in MacOS if not from Homebrew?

Pyenv can compile OpenSSL and Readline from source and take Zlib from XCode SDK. What about others?

**Comment by native-api** [comment]
As an alternative solution, there's a 3rd-party plugin, https://github.com/sprout42/pyenv-fix-version, that recompiles installed Pythons if the underlying deps have been upgraded.

**Comment by native-api** [comment]
> Where are you going to take deps from in MacOS if not from Homebrew?
> 
> Pyenv can compile OpenSSL and Readline from source and take Zlib from XCode SDK. What about others?

AFAICS, according to https://news.ycombinator.com/item?id=9407119, there's smth called "pkgsrc" which is stable release instead of rolling release.

**Comment by native-api** [comment]
The breakage you're describing is what you get when you're dealing with rolling-release stuff. You _have_ to sync all your dependent software whenever you do an upgrade or you risk this.

So it's either
* switch to a stable-release product (and miss out on new versions of libs that might be needed for new versions of Python), or
* introduce extra complexity and sync all your stuff (which is Pythons and their Pip-installed extension modules) to the rolling-release ecosystem at every upgrade

**Comment by sivel** [comment]
> Where are you going to take deps from in MacOS if not from Homebrew?
> 
> Pyenv can compile OpenSSL and Readline from source and take Zlib from XCode SDK. What about others?

What does it matter where they come from? If a user wants more control over handling deps, give them a way to do so.  It's not the default behavior, nor should you be concerned about offering instructions to users that want a way to prevent using homebrew.

Simply, the desire is to give the user the option to handle the deps themselves, in whatever way they desire.  Just because homebrew is installed, and I am running macos, doesn't mean I want pyenv to magically assume that I want to use homebrew for the deps.

**Comment by native-api** [comment]
> What does it matter where they come from? If a user wants more control over handling deps, give them a way to do so. It's not the default behavior, nor should you be concerned about offering instructions to users that want a way to prevent using homebrew.
> 
> Simply, the desire is to give the user the option to handle the deps themselves, in whatever way they desire. Just because homebrew is installed, and I am running macos, doesn't mean I want pyenv to magically assume that I want to use homebrew for the deps.

Okay, that makes sense. The normal software build behavior is to take whatever is available on the configured/default search paths -- and let the user arrange them as needed. But the Homebrew search behavior is not a part of that.

My primary concern was that there's simply nothing else realistically available in MacOS to get the dependencies from that is any better than Homebrew for your use case (which would make this use case rather unrealistic thus probably not worth supporting). But now that we see there is, that's not a problem.

---

The envvars would need to be prefixed with `PYTHON_BUILD_` like other envs that affect the build (see https://github.com/pyenv/pyenv/tree/master/plugins/python-build#readme).

**Comment by samdoran** [comment]
I'll change the var name and add docs.

**Comment by samdoran** [comment]
Thank you so much!

**Pull request merged**
